//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSoft.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelSoft.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous generic base type or interface found.
        /// </summary>
        public static string AmbiguousGenericBaseCandidates {
            get {
                return ResourceManager.GetString("AmbiguousGenericBaseCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string ArgException_Collection {
            get {
                return ResourceManager.GetString("ArgException_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not meet the condition: {1}..
        /// </summary>
        public static string ArgException_ConditionIsNotMeet {
            get {
                return ResourceManager.GetString("ArgException_ConditionIsNotMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has invalid {1} value. Actual value is: {2}..
        /// </summary>
        public static string ArgException_EnumIsNotValid {
            get {
                return ResourceManager.GetString("ArgException_EnumIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found: {1}.
        /// </summary>
        public static string ArgException_KeyNotFound {
            get {
                return ResourceManager.GetString("ArgException_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string ArgException_Max {
            get {
                return ResourceManager.GetString("ArgException_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string ArgException_Min {
            get {
                return ResourceManager.GetString("ArgException_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not match condition..
        /// </summary>
        public static string ArgException_NotAllElementsMatchCondition {
            get {
                return ResourceManager.GetString("ArgException_NotAllElementsMatchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be empty..
        /// </summary>
        public static string ArgException_StringIsNotEmpty {
            get {
                return ResourceManager.GetString("ArgException_StringIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be blank..
        /// </summary>
        public static string ArgException_StringIsNotWhitespace {
            get {
                return ResourceManager.GetString("ArgException_StringIsNotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrogates not allowed as single char..
        /// </summary>
        public static string ArgException_SurrogateNotAllowedAsSingleChar {
            get {
                return ResourceManager.GetString("ArgException_SurrogateNotAllowedAsSingleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ArgException_Value {
            get {
                return ResourceManager.GetString("ArgException_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be lesser than or equal to {2}. Actual value is {1}..
        /// </summary>
        public static string ArgOutOfRange_MaxMsg {
            get {
                return ResourceManager.GetString("ArgOutOfRange_MaxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {3}. Actual value is {1}..
        /// </summary>
        public static string ArgOutOfRange_MinMaxMsg {
            get {
                return ResourceManager.GetString("ArgOutOfRange_MinMaxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} must be ordered. Actual values are {2} and {3}..
        /// </summary>
        public static string ArgOutOfRange_MinMaxValidMsg {
            get {
                return ResourceManager.GetString("ArgOutOfRange_MinMaxValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {2}. Actual value is {1}..
        /// </summary>
        public static string ArgOutOfRange_MinMsg {
            get {
                return ResourceManager.GetString("ArgOutOfRange_MinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string EnumerableExtensions_Periods {
            get {
                return ResourceManager.GetString("EnumerableExtensions_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum {0} must have at least one literal.
        /// </summary>
        public static string EnumMustHaveOneLiteral {
            get {
                return ResourceManager.GetString("EnumMustHaveOneLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} forms a cycle with its base classes..
        /// </summary>
        public static string ExMsg_BaseClassCycle {
            get {
                return ResourceManager.GetString("ExMsg_BaseClassCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrementing {0} is out of range for type {1}.
        /// </summary>
        public static string ExMsg_DecrementOutOfRange {
            get {
                return ResourceManager.GetString("ExMsg_DecrementOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default instance is already setup..
        /// </summary>
        public static string ExMsg_DefaultInstanceAlreadySetUp {
            get {
                return ResourceManager.GetString("ExMsg_DefaultInstanceAlreadySetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory do not exist: {0}.
        /// </summary>
        public static string ExMsg_DirectoryDoNotExist {
            get {
                return ResourceManager.GetString("ExMsg_DirectoryDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not support binary serialization.
        /// </summary>
        public static string ExMsg_DoNotSupportBinarySerialization {
            get {
                return ResourceManager.GetString("ExMsg_DoNotSupportBinarySerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not support value comparison.
        /// </summary>
        public static string ExMsg_DoNotSupportCompare {
            get {
                return ResourceManager.GetString("ExMsg_DoNotSupportCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not support increment/decrement.
        /// </summary>
        public static string ExMsg_DoNotSupportIncrementDecrement {
            get {
                return ResourceManager.GetString("ExMsg_DoNotSupportIncrementDecrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not support string serialization.
        /// </summary>
        public static string ExMsg_DoNotSupportStringSerialization {
            get {
                return ResourceManager.GetString("ExMsg_DoNotSupportStringSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one duplicated object in collection {0}: {1}.
        /// </summary>
        public static string ExMsg_DuplicatedObjectsInCollection {
            get {
                return ResourceManager.GetString("ExMsg_DuplicatedObjectsInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one duplicated {0} in collection {1}: {2}.
        /// </summary>
        public static string ExMsg_DuplicatedPropertyInCollection {
            get {
                return ResourceManager.GetString("ExMsg_DuplicatedPropertyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection..
        /// </summary>
        public static string ExMsg_EnumerableExtensions_EmptyCollection {
            get {
                return ResourceManager.GetString("ExMsg_EnumerableExtensions_EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection cannot have a minimum..
        /// </summary>
        public static string ExMsg_EnumerableExtensions_EmptyCollectionNoMinException {
            get {
                return ResourceManager.GetString("ExMsg_EnumerableExtensions_EmptyCollectionNoMinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching element found..
        /// </summary>
        public static string ExMsg_EnumerableExtensions_NoMatchingElementException {
            get {
                return ResourceManager.GetString("ExMsg_EnumerableExtensions_NoMatchingElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enum type cannot have {1} as base type..
        /// </summary>
        public static string ExMsg_EnumTypeCannotHaveTypeAsBaseType {
            get {
                return ResourceManager.GetString("ExMsg_EnumTypeCannotHaveTypeAsBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enum type requires at least one literal..
        /// </summary>
        public static string ExMsg_EnumTypeRequiresAtLeastOneLiteral {
            get {
                return ResourceManager.GetString("ExMsg_EnumTypeRequiresAtLeastOneLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incrementing {0} is out of range for type {1}.
        /// </summary>
        public static string ExMsg_IncrementOutOfRange {
            get {
                return ResourceManager.GetString("ExMsg_IncrementOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid freezing operation..
        /// </summary>
        public static string ExMsg_InvalidFreezingOperationException {
            get {
                return ResourceManager.GetString("ExMsg_InvalidFreezingOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid setup.
        /// </summary>
        public static string ExMsg_InvalidSetUp {
            get {
                return ResourceManager.GetString("ExMsg_InvalidSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting source item..
        /// </summary>
        public static string ExMsg_ItemConverterBase_ErrorConvertingSource {
            get {
                return ResourceManager.GetString("ExMsg_ItemConverterBase_ErrorConvertingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be frozen in order to be used as the meta class of an object..
        /// </summary>
        public static string ExMsg_MetaClassMustBeFrozen {
            get {
                return ResourceManager.GetString("ExMsg_MetaClassMustBeFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing enum base value on literal {0}.
        /// </summary>
        public static string ExMsg_MissingEnumLiteralValue {
            get {
                return ResourceManager.GetString("ExMsg_MissingEnumLiteralValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be frozen to access this feature:{0}.
        /// </summary>
        public static string ExMsg_ObjectMustBeFrozen {
            get {
                return ResourceManager.GetString("ExMsg_ObjectMustBeFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional value has no value..
        /// </summary>
        public static string ExMsg_Optional_HasNoValueException {
            get {
                return ResourceManager.GetString("ExMsg_Optional_HasNoValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        public static string ExMsg_PropertyCannotBeEmpty {
            get {
                return ResourceManager.GetString("ExMsg_PropertyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        public static string ExMsg_PropertyCannotBeNull {
            get {
                return ResourceManager.GetString("ExMsg_PropertyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be blank..
        /// </summary>
        public static string ExMsg_PropertyCannotBeWhitespace {
            get {
                return ResourceManager.GetString("ExMsg_PropertyCannotBeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change value..
        /// </summary>
        public static string ExMsg_Reference_CanChangeValue {
            get {
                return ResourceManager.GetString("ExMsg_Reference_CanChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated key not allowed on trie..
        /// </summary>
        public static string ExMsg_TrieNode_DuplicatedKeyNotAllowed {
            get {
                return ResourceManager.GetString("ExMsg_TrieNode_DuplicatedKeyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not conformant with data type {1}..
        /// </summary>
        public static string ExMsg_ValueIsNotConformantWithDataType {
            get {
                return ResourceManager.GetString("ExMsg_ValueIsNotConformantWithDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing enum base value {0} on literal {1}.
        /// </summary>
        public static string ExMsg_WrongEnumLiteralValue {
            get {
                return ResourceManager.GetString("ExMsg_WrongEnumLiteralValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier: &quot;{0}&quot;.
        /// </summary>
        public static string InvalidCSharpIdentifier {
            get {
                return ResourceManager.GetString("InvalidCSharpIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run more than {0} depth of actions..
        /// </summary>
        public static string MetaModelActionsLogicTooDeep {
            get {
                return ResourceManager.GetString("MetaModelActionsLogicTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No candidate generic base type or interface found.
        /// </summary>
        public static string NoGenericBaseCandidateFound {
            get {
                return ResourceManager.GetString("NoGenericBaseCandidateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a generic type: {0}.
        /// </summary>
        public static string NotAGenericType {
            get {
                return ResourceManager.GetString("NotAGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a generic type definition: {0}.
        /// </summary>
        public static string NotAGenericTypeDefinition {
            get {
                return ResourceManager.GetString("NotAGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        public static string NullString {
            get {
                return ResourceManager.GetString("NullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no value).
        /// </summary>
        public static string Optional_NoHasValueToString {
            get {
                return ResourceManager.GetString("Optional_NoHasValueToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer for type {0} not found.
        /// </summary>
        public static string SerializerForTypeNotFound {
            get {
                return ResourceManager.GetString("SerializerForTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type {0} do not implement IModelDefinition interface.
        /// </summary>
        public static string TypeDoNotImplementModelDefinition {
            get {
                return ResourceManager.GetString("TypeDoNotImplementModelDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type {0} is not an interface.
        /// </summary>
        public static string TypeIsNotAnInterface {
            get {
                return ResourceManager.GetString("TypeIsNotAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given value is not an instance of {0}: {1}.
        /// </summary>
        public static string ValueIsNotInstanceOfType {
            get {
                return ResourceManager.GetString("ValueIsNotInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable or expression does not meet required condition.
        /// </summary>
        public static string VarOrExprDoNotMeetCondition {
            get {
                return ResourceManager.GetString("VarOrExprDoNotMeetCondition", resourceCulture);
            }
        }
    }
}
